---
title: "Podstawy programowania w R - Zadanie zaliczeniowe nr 2"
author: "Szymon Nowakowski"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


#code from https://selbydavid.com/2017/06/18/rmarkdown-alerts/
knitr::knit_hooks$set(
   error = function(x, options) {
     paste('\n\n<div class="alert alert-danger">',
           gsub('##', '\n', gsub('^##\ Error', '**Error**', x)),
           '</div>', sep = '\n')
   },
   warning = function(x, options) {
     paste('\n\n<div class="alert alert-warning">',
           gsub('##', '\n', gsub('^##\ Warning:', '**Warning**', x)),
           '</div>', sep = '\n')
   },
   message = function(x, options) {
     paste('\n\n<div class="alert alert-info">',
           gsub('##', '\n', x),
           '</div>', sep = '\n')
   }
)

```



## Zasady zaliczania przedmiotu *Podstawy programowania R*

Zaliczenie przedmiotu, zgodnie z USOS, odbywa się poprzez rozwiązanie i zaliczenie **dwóch** zadań programistycznych.

Dodatkowo, co najmniej jedno z tych zadań musi zostać zaprezentowane prowadzącemu w postaci około 10 minutowej rozmowy n.t. Waszego rozwiązania. Mogą Państwo wybrać, które zadanie zaprezentujecie. **Prezentacja jest warunkiem koniecznym zaliczenia przedmiotu**. Jeśli nie będziecie Państwo zadowoleni z przebiegu pierwszej prezentacji, macie prawo zaprezentować drugie zadanie.

W ramach rozwiązania każdego z dwóch zadań powinien powstać dokument w RMarkdown (**czyli .Rmd**, a nie .html). Dokument ten należy przesłać mailowo na adres email *s.nowakowski@mimuw.edu.pl*, tytuł maila: **"Zadanie zaliczeniowe nr ..."**.

- Ostatecznym terminem nadsyłania rozwiązań zadania numer 1 jest wtorek 17.01.2023, 23:59.
- Ostatecznym terminem nadsyłania rozwiązań zadania numer 2 jest wtorek 24.01.2023, 23:59.
- Ostatecznym możliwym terminem prezentacji jest wtorek 24.01.2023, godz 14.00.

Rozwiązania zadań nadesłane po terminie nie będą brane pod uwagę przy ocenie.

Termin prezentacji mogą Państwo wybrać spośród następujących terminów:

- w czasie zajęć, jeśli grupa jest zajęta pracą własną (lub w czasie przerwy między zajęciami obu grup),
- termin konsultacji na Wydziale Dziennikarstwa, Informacji i Bibliologii, każdy wtorek 13.00-14.00 (konieczny jest własny laptop studenta),
- termin konsultacji na Wydziale Matematyki, Informatyki i Mechaniki, ul. Banacha 2, pokój 4250, każdy poniedziałek 15.45-16.45,
- **sobota 14.01.2023 w godzinach 10.00-16.00** w Budynku Wydziału Fizyki, ul. Pasteura 5, pokój B.239a (II. piętro), 
- **sobota 21.01.2023 w godzinach 10.00-16.00** w Budynku Wydziału Fizyki, ul. Pasteura 5, pokój B.239a (II. piętro).

Osoby, które nie zaliczą w terminie, będą miały możliwość zaliczenia przedmiotu w *sesji poprawkowej*.

```
Zgodnie z uchwałami Rad Dydaktycznych ws. zasad przeprowadzania egzaminów na Państwa Wydziale zaliczenie na ocenę odbywa się przed sesją (§10: zaliczenie na ocenę w pierwszym terminie odbywa się w czasie ostatnich zajęć lub w okresie przed rozpoczęciem sesji egzaminacyjnej. Termin poprawkowy zaliczenia na ocenę powinien być wyznaczony w poprawkowej sesji egzaminacyjnej).
```
# Zadanie Zaliczeniowe nr 2

## Kontekst zadania zaliczeniowego

W mojej pracy naukowej pracuję z danymi kategorycznymi (typ `factor`). W dotychczasowej pracy wykorzystałem następujące zbiory danych:

1. Insurance - https://www.kaggle.com/c/prudential-life-insurance-assessment/data,

2. Antigua - dane `antigua` z pakietu `DAAG` w R,

3. Airbnb - strona internetowa insideairbnb.com, zrzut danych z konkretnej daty,

4. Promoter - https://archive.ics.uci.edu/ml/datasets/Molecular+Biology+%28Promoter+Gene+Sequences%29,

5. Adult - https://archive.ics.uci.edu/ml/datasets/Adult.

## Ogólny opis zadania zaliczeniowego

Zadanie zaliczeniowe nr 2 polega na przejrzeniu przez studentów następujących repozytoriów danych:

1. Kaggle https://www.kaggle.com/

2. Machine Learning Repository https://archive.ics.uci.edu/

3. Pakiety R

4. Inne - liczę tu na Państwa pomysłowość

Studenci powinni krytycznie przejrzeć dostępne zbiory danych i zidentyfikować jeden lub więcej zbiorów danych (innych niż 5 podanych wyżej), spełniających możliwie jak najdokładniej następujące kryteria:

- Główna zmienna modelowana w danym zbiorze danych powinna być albo ciągła (typ `numeric`) albo powinna mieć dwie klasy (typ `factor` z dwoma poziomami lub tylko dwie wartości np. 0 i 1). Informację, jaką zmienną modeluje dany zbiór danych można znaleźć w opisie, lub użyć zdrowego rozsądku. 

  Przykładowo, w znanych mi już 5 zbiorach danych, główna zmienna modelowana przez dane jest następująca:
  
  
  - **Insurance** - kolumna `Response`: zmienna mierząca poziom ryzyka przypisanego aplikantowi ubezpieczeniowemu w postaci liczby całkowitej 1-8. W istocie jest to zmienna określająca jedną z ośmiu klas, ale ze względu na dużą liczbę klas (osiem) i uporządkowanie tych klas (typ `factor` z flagą `ordered`), traktuję tę zmienną jak zmienną ciągłą. 
  
  - Podobna sytuacja mogłaby wystąpić np. przy ocenie filmów w postaci 1-5 gwiazdek. Formalnie jest to zmienna typu `factor` o 5 poziomach, ale taką zmienną można (po uprzednim wyjaśnieniu sytuacji) potraktować jak zmienną ciągłą.
  
  - **Antigua** - główna zmienna modelowana w danych to zmienna `harvwt`, która mierzy poziom zbioru kukurydzy na wyspie Antigua. Jest to zmienna ciągła.

  - **Airbnb** - zbiór danych podaje cenę najmu krótkoterminowego mieszkań w zależności od takich cech jak sąsiedztwo, liczba pokoi, czy jest przyjazne dzieciom itd. Tak więc główną modelowaną zmienną jest cena najmu (ang. *price*). Jest to zmienna ciągła.

  - **Promoter** - główna zmienna modelowana ma dwie klasy: dana sekwencja jest promotorowa (wartość `+`) lub nie jest promotorowa (wartość `-`).

  - **Adult** - główna zmienna modelowana to przychód, ma ona dwie klasy: badany zarabia ponad 50k (wartość `>50K`) USD rocznie lub nie (wartość `<=50K`).

- Pozostałe (poza główną) kolumny w danych to dodatkowe atrybuty. Te atrybuty mogą być albo ciągłe (typ `numeric`) albo kategoryczne (typ `factor`). W danych powinna być przynajmniej jedna kolumna kategoryczna. Nie interesują nas opisy, komentarze itd, czyli nieustrukturyzowane kolumny opisowe. Mogą one wystąpić w danych, ale nie ma to dla nas wartości. 

- Interesują mnie zmienne kategoryczne. Dlatego dodatkowe atrybuty kategoryczne powinny być jak najbardziej liczne lub mieć jak najwięcej poziomów (im więcej, tym lepiej, poziomy mogą być liczone łącznie). 

  Przykładowo, w znanych mi już danych sytuacja przedstawia się następująco:
  
  
  - **Insurance** - 5 zmiennych ciągłych i 108 kategorycznych, łącznie mających 925 poziomów,
  
  - **Antigua** - 1 zmienna ciągła i 4 kategoryczne (`plot` traktujemy jako zmienną kategoryczną, `id` usuwamy z analizy), łącznie o 60 poziomach,

  - **Airbnb** - 764 kolumny ciągłe i 3 kolumny kategoryczne mające 39393, 311 i 204 poziomów.

  - **Promoter** - 57 zmiennych kategorycznych, każda o 4 poziomach (wartości `a`, `g`, `t`, `c`),

  - **Adult** - 2 zmienne ciągłe i 8 kategorycznych, łącznie mających 98 poziomów.

- Badane dane powinny mieć jak najwięcej wierszy (tzn. obserwacji). Przykładowo, dane Airbnb, Adult i Insurance mają kilkadziesiąt tysięcy wierszy każdy. Faktem jest też, że dane Antigua i Promoter mają zaledwie 287 i 106 obserwacji, odpowiednio, nie spełniają zatem tego wymagania w stopniu dostatecznym.
  
- Badane dane **nie** powinny być szeregiem czasowym (ang. *time series*). W szeregu czasowym kolejne kolumny określają wartość w kolejnych punktach w czasie. Takie dane nas **nie** interesują.

- Badane dane **nie** powinny być obrazami (zdjęciami, rysunkami, etc.).

Jak widzicie Państwo z podanych wyżej przykładów znanych mi 5 zbiorów, powyższe kryteria są w istocie wskazówkami, czego szukać, a nie sztywnymi wymaganiami. Niektóre ze znanych mi 5 zbiorów danych spełniają jedno lub więcej z powyższych kryteriów w sposób jedynie przybliżony. **Jedynie w przypadku dwóch ostatnich kryteriów proszę o ich bezwzględne spełnienie.**

## Szczegółowy opis wyniku zadania zaliczeniowego

W ramach rozwiązania zadania powinien powstać dokument w RMarkdown (**czyli .Rmd**, a nie .html). 

Dokument ten powinien dokumentować proces przeszukiwania podanych repozytoriów, tzn. 

- wymienić ewentualne kryteria wyszukiwania zbiorów danych (jeśli dane repozytorium oferuje automatyczną przeszukiwarkę); 

- wymienić przejrzane i odrzucone zbiory danych, wraz z ich adresem oraz podaniem przyczyny odrzucenia (może być skwitowane jednym zdaniem lub równoważnikiem zdania, np. "szereg czasowy", "brak zmiennych kategorycznych", "zbyt mało poziomów", etc.). Ta część może być zorganizowana dla czytelności w postaci tabeli z 3 kolumnami - nazwa zbioru danych, adres, przyczyna odrzucenia;

- wymienić i skrótowo opisać te zbiory danych, które dobrze rokują spełnienie wymagań. Może ich być kilka;

- szczegółowo opisać jeden wybrany najlepszy zbiór danych. **To najważniejsza część Państwa analizy**.

  1. Opisz, jak odczytujesz dane. Opisz argumenty zastosowane przy wywołaniu funkcji. Pamiętaj, że jeżeli dane składają się z kilku części (np. autorzy zbioru danych podzielili dane na część treningową i testową), opisz jak je łączysz i połącz te dane razem, gdyż nas ten podział nie interesuje.
  
  2. Omów odczytane dane. Która kolumna jest według Ciebie główną kolumną modelowaną przez dane, a które kolumny dostarczają dodatkowych atrybutów danych.
  
  2. Pokaż statystyki odczytanych danych (ile jest wierszy, jakiego typu jest główna kolumna w danych, a jakich typów są pozostałe kolumny, główne statystyki dotyczące każdej kolumny).
  
  3. Omów brakujące dane. Jeśli dotyczą tylko kilku kolumn, może warto omówić je per kolumna? 
  
  4. Sprawdź, czy w różnych kolumnach nie są prezentowane te same dane, ale w inny sposób kodowane lub obliczone poprzez proste przekształcenie funkcyjne. Omów takie sytuacje.
  
     Przykładowo, jeśli są dwie kolumny `weight` oraz `low`, gdzie `weight` podaje wagę urodzeniową noworodka, zaś `low` podaje w formie zero-jedynkowej, czy waga urodzeniowa była mniejsza niż 2500g, to w sposób oczywisty dane są zdublowane w kolumnie `low`. 
     
     Inny przykład: kolumna kwota transakcji w postaci liczby i druga kolumna określająca kwotę transakcji słownie niosą w istocie tę samą informację, przy czym do analizy wygodniejsza jest liczba (kolumna kwota transakcji słownie jest w gruncie rzeczy nieustrukturyzowaną kolumną tekstową).
     
  5. Omów kwestię ewentualnych danych odstających. Dane odstające możesz zidentyfikować na wykresach. 
  
  6. Jeśli uznasz, że warto, zaprezentuj wczytane dane lub ich wycinek przy użyciu wykresów, które będą **czytelnie** przekazywać możliwie najwięcej informacji o danych zachowując estetyczną formę.

  7. Nie interesują nas opisy, komentarze itd, czyli nieustrukturyzowane kolumny tekstowe. Takie kolumny należy wymienić w opisie, ale proszę nie poświęcajcie im poza tym czasu. 

**Pamiętaj!**

1. Jeśli potrafisz, wstaw do dokumentu lub wykresów wzory matematyczne, ale nie na siłę. **Pamiętaj, że to praca z R, nie z Latexa**.
  
2. Niech RMarkdown będzie czytelny, stosuj z umiarem elementy formatowania, ale nic na siłę: **to praca z R, nie z Markdownu**.

## Dodatkowe informacje

Wierzę w transparentne zasady. Studenci, których analiza zostanie użyta w mojej pracy naukowej, zostaną wymienieni w podziękowaniach ewentualnych publikacji. Jeśli wykorzystam fragmenty Państwa kodu dotyczące odczytu lub prezentacji danych, zostaniecie współautorami powstałej publikacji. Dlatego **proszę o podanie emaila kontaktowego w dokumencie .Rmd**.
  
